<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = DB::table('cities')->insert([
            array('id' => '1', 'name' => 'Adilabad', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '2', 'name' => 'Anantapur', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '3', 'name' => 'Chittoor', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '4', 'name' => 'Kakinada', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '5', 'name' => 'Guntur', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '6', 'name' => 'Hyderabad', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '7', 'name' => 'Karimnagar', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '8', 'name' => 'Khammam', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '9', 'name' => 'Krishna', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '10', 'name' => 'Kurnool', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '11', 'name' => 'Mahbubnagar', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '12', 'name' => 'Medak', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'name' => 'Nalgonda', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '14', 'name' => 'Nizamabad', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '15', 'name' => 'Ongole', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '16', 'name' => 'Hyderabad', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '17', 'name' => 'Srikakulam', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '18', 'name' => 'Nellore', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '19', 'name' => 'Visakhapatnam', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '20', 'name' => 'Vizianagaram', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '21', 'name' => 'Warangal', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '22', 'name' => 'Eluru', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '23', 'name' => 'Kadapa', 'state_id' => '2', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '24', 'name' => 'Anjaw', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '25', 'name' => 'Changlang', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '26', 'name' => 'East Siang', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '27', 'name' => 'Kurung Kumey', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '28', 'name' => 'Lohit', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '29', 'name' => 'Lower Dibang Valley', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '30', 'name' => 'Lower Subansiri', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '31', 'name' => 'Papum Pare', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '32', 'name' => 'Tawang', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '33', 'name' => 'Tirap', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '34', 'name' => 'Dibang Valley', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '35', 'name' => 'Upper Siang', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '36', 'name' => 'Upper Subansiri', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '37', 'name' => 'West Kameng', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '38', 'name' => 'West Siang', 'state_id' => '3', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '39', 'name' => 'Baksa', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '40', 'name' => 'Barpeta', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '41', 'name' => 'Bongaigaon', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '42', 'name' => 'Cachar', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '43', 'name' => 'Chirang', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '44', 'name' => 'Darrang', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '45', 'name' => 'Dhemaji', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '46', 'name' => 'Dima Hasao', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '47', 'name' => 'Dhubri', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '48', 'name' => 'Dibrugarh', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '49', 'name' => 'Goalpara', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '50', 'name' => 'Golaghat', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '51', 'name' => 'Hailakandi', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '52', 'name' => 'Jorhat', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '53', 'name' => 'Kamrup', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '54', 'name' => 'Kamrup Metropolitan', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '55', 'name' => 'Karbi Anglong', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '56', 'name' => 'Karimganj', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '57', 'name' => 'Kokrajhar', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '58', 'name' => 'Lakhimpur', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '59', 'name' => 'Marigaon', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '60', 'name' => 'Nagaon', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '61', 'name' => 'Nalbari', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '62', 'name' => 'Sibsagar', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '63', 'name' => 'Sonitpur', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '64', 'name' => 'Tinsukia', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '65', 'name' => 'Udalguri', 'state_id' => '4', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '66', 'name' => 'Araria', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '67', 'name' => 'Arwal', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '68', 'name' => 'Aurangabad', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '69', 'name' => 'Banka', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '70', 'name' => 'Begusarai', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '71', 'name' => 'Bhagalpur', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '72', 'name' => 'Bhojpur', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '73', 'name' => 'Buxar', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '74', 'name' => 'Darbhanga', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '75', 'name' => 'East Champaran', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '76', 'name' => 'Gaya', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '77', 'name' => 'Gopalganj', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '78', 'name' => 'Jamui', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '79', 'name' => 'Jehanabad', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '80', 'name' => 'Kaimur', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '81', 'name' => 'Katihar', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '82', 'name' => 'Khagaria', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '83', 'name' => 'Kishanganj', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '84', 'name' => 'Lakhisarai', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '85', 'name' => 'Madhepura', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '86', 'name' => 'Madhubani', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '87', 'name' => 'Munger', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '88', 'name' => 'Muzaffarpur', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '89', 'name' => 'Nalanda', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '90', 'name' => 'Nawada', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '91', 'name' => 'Patna', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '92', 'name' => 'Purnia', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '93', 'name' => 'Rohtas', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '94', 'name' => 'Saharsa', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '95', 'name' => 'Samastipur', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '96', 'name' => 'Saran', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '97', 'name' => 'Sheikhpura', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '98', 'name' => 'Sheohar', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '99', 'name' => 'Sitamarhi', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '100', 'name' => 'Siwan', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '101', 'name' => 'Supaul', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '102', 'name' => 'Vaishali', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '103', 'name' => 'West Champaran', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '104', 'name' => 'Chandigarh', 'state_id' => '5', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '105', 'name' => 'Bastar', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '106', 'name' => 'Bijapur', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '107', 'name' => 'Bilaspur', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '108', 'name' => 'Dantewada', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '109', 'name' => 'Dhamtari', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '110', 'name' => 'Durg', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '111', 'name' => 'Jashpur', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '112', 'name' => 'Janjgir-Champa', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '113', 'name' => 'Korba', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '114', 'name' => 'Koriya', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '115', 'name' => 'Kanker', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '116', 'name' => 'Kabirdham (Kawardha)', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '117', 'name' => 'Mahasamund', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '118', 'name' => 'Narayanpur', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '119', 'name' => 'Raigarh', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '120', 'name' => 'Rajnandgaon', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '121', 'name' => 'Raipur', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '122', 'name' => 'Surguja', 'state_id' => '7', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '123', 'name' => 'Central Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '124', 'name' => 'East Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '125', 'name' => 'New Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '126', 'name' => 'North Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '127', 'name' => 'North East Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '128', 'name' => 'North West Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '129', 'name' => 'South Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '130', 'name' => 'South West Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '131', 'name' => 'West Delhi', 'state_id' => '10', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '132', 'name' => 'North Goa', 'state_id' => '11', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '133', 'name' => 'South Goa', 'state_id' => '11', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '134', 'name' => 'Ahmedabad', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '135', 'name' => 'Amreli district', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '136', 'name' => 'Anand', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '137', 'name' => 'Banaskantha', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '138', 'name' => 'Bharuch', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '139', 'name' => 'Bhavnagar', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '140', 'name' => 'Dahod', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '141', 'name' => 'The Dangs', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '142', 'name' => 'Gandhinagar', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '143', 'name' => 'Jamnagar', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '144', 'name' => 'Junagadh', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '145', 'name' => 'Kutch', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '146', 'name' => 'Kheda', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '147', 'name' => 'Mehsana', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '148', 'name' => 'Narmada', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '149', 'name' => 'Navsari', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '150', 'name' => 'Patan', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '151', 'name' => 'Panchmahal', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '152', 'name' => 'Porbandar', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '153', 'name' => 'Rajkot', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '154', 'name' => 'Sabarkantha', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '155', 'name' => 'Surendranagar', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '156', 'name' => 'Surat', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '157', 'name' => 'Vyara', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '158', 'name' => 'Vadodara', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '159', 'name' => 'Valsad', 'state_id' => '12', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '160', 'name' => 'Ambala', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '161', 'name' => 'Bhiwani', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '162', 'name' => 'Faridabad', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '163', 'name' => 'Fatehabad', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '164', 'name' => 'Gurgaon', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '165', 'name' => 'Hissar', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '166', 'name' => 'Jhajjar', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '167', 'name' => 'Jind', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '168', 'name' => 'Karnal', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '169', 'name' => 'Kaithal', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '170', 'name' => 'Kurukshetra', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '171', 'name' => 'Mahendragarh', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '172', 'name' => 'Mewat', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '173', 'name' => 'Palwal', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '174', 'name' => 'Panchkula', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '175', 'name' => 'Panipat', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '176', 'name' => 'Rewari', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '177', 'name' => 'Rohtak', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '178', 'name' => 'Sirsa', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '179', 'name' => 'Sonipat', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '180', 'name' => 'Yamuna Nagar', 'state_id' => '13', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '181', 'name' => 'Bilaspur', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '182', 'name' => 'Chamba', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '183', 'name' => 'Hamirpur', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '184', 'name' => 'Kangra', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '185', 'name' => 'Kinnaur', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '186', 'name' => 'Kullu', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '187', 'name' => 'Lahaul and Spiti', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '188', 'name' => 'Mandi', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '189', 'name' => 'Shimla', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '190', 'name' => 'Sirmaur', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '191', 'name' => 'Solan', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '192', 'name' => 'Una', 'state_id' => '14', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '193', 'name' => 'Anantnag', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '194', 'name' => 'Badgam', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '195', 'name' => 'Bandipora', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '196', 'name' => 'Baramulla', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '197', 'name' => 'Doda', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '198', 'name' => 'Ganderbal', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '199', 'name' => 'Jammu', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '200', 'name' => 'Kargil', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '201', 'name' => 'Kathua', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '202', 'name' => 'Kishtwar', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '203', 'name' => 'Kupwara', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '204', 'name' => 'Kulgam', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '205', 'name' => 'Leh', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '206', 'name' => 'Poonch', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '207', 'name' => 'Pulwama', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '208', 'name' => 'Rajauri', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '209', 'name' => 'Ramban', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '210', 'name' => 'Reasi', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '211', 'name' => 'Samba', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '212', 'name' => 'Shopian', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '213', 'name' => 'Srinagar', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '214', 'name' => 'Udhampur', 'state_id' => '15', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '215', 'name' => 'Bokaro', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '216', 'name' => 'Chatra', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '217', 'name' => 'Deoghar', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '218', 'name' => 'Dhanbad', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '219', 'name' => 'Dumka', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '220', 'name' => 'East Singhbhum', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '221', 'name' => 'Garhwa', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '222', 'name' => 'Giridih', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '223', 'name' => 'Godda', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '224', 'name' => 'Gumla', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '225', 'name' => 'Hazaribag', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '226', 'name' => 'Jamtara', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '227', 'name' => 'Khunti', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '228', 'name' => 'Koderma', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '229', 'name' => 'Latehar', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '230', 'name' => 'Lohardaga', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '231', 'name' => 'Pakur', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '232', 'name' => 'Palamu', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '233', 'name' => 'Ramgarh', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '234', 'name' => 'Ranchi', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '235', 'name' => 'Sahibganj', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '236', 'name' => 'Seraikela Kharsawan', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '237', 'name' => 'Simdega', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '238', 'name' => 'West Singhbhum', 'state_id' => '16', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '239', 'name' => 'Bagalkot', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '240', 'name' => 'Bangalore Rural', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '241', 'name' => 'Bangalore Urban', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '242', 'name' => 'Belgaum', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '243', 'name' => 'Bellary', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '244', 'name' => 'Bidar', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '245', 'name' => 'Bijapur', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '246', 'name' => 'Chamarajnagar', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '247', 'name' => 'Chikkamagaluru', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '248', 'name' => 'Chikkaballapur', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '249', 'name' => 'Chitradurga', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '250', 'name' => 'Davanagere', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '251', 'name' => 'Dharwad', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '252', 'name' => 'Dakshina Kannada', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '253', 'name' => 'Gadag', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '254', 'name' => 'Gulbarga', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '255', 'name' => 'Hassan', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '256', 'name' => 'Haveri district', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '257', 'name' => 'Kodagu', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '258', 'name' => 'Kolar', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '259', 'name' => 'Koppal', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '260', 'name' => 'Mandya', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '261', 'name' => 'Mysore', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '262', 'name' => 'Raichur', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '263', 'name' => 'Shimoga', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '264', 'name' => 'Tumkur', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '265', 'name' => 'Udupi', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '266', 'name' => 'Uttara Kannada', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '267', 'name' => 'Ramanagara', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '268', 'name' => 'Yadgir', 'state_id' => '17', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '269', 'name' => 'Alappuzha', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '270', 'name' => 'Ernakulam', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '271', 'name' => 'Idukki', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '272', 'name' => 'Kannur', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '273', 'name' => 'Kasaragod', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '274', 'name' => 'Kollam', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '275', 'name' => 'Kottayam', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '276', 'name' => 'Kozhikode', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '277', 'name' => 'Malappuram', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '278', 'name' => 'Palakkad', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '279', 'name' => 'Pathanamthitta', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '280', 'name' => 'Thrissur', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '281', 'name' => 'Thiruvananthapuram', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '282', 'name' => 'Wayanad', 'state_id' => '18', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '283', 'name' => 'Alirajpur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '284', 'name' => 'Anuppur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '285', 'name' => 'Ashok Nagar', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '286', 'name' => 'Balaghat', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '287', 'name' => 'Barwani', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '288', 'name' => 'Betul', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '289', 'name' => 'Bhind', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '290', 'name' => 'Bhopal', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '291', 'name' => 'Burhanpur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '292', 'name' => 'Chhatarpur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '293', 'name' => 'Chhindwara', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '294', 'name' => 'Damoh', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '295', 'name' => 'Datia', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '296', 'name' => 'Dewas', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '297', 'name' => 'Dhar', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '298', 'name' => 'Dindori', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '299', 'name' => 'Guna', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '300', 'name' => 'Gwalior', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '301', 'name' => 'Harda', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '302', 'name' => 'Hoshangabad', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '303', 'name' => 'Indore', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '304', 'name' => 'Jabalpur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '305', 'name' => 'Jhabua', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '306', 'name' => 'Katni', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '307', 'name' => 'Khandwa (East Nimar)', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '308', 'name' => 'Khargone (West Nimar)', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '309', 'name' => 'Mandla', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '310', 'name' => 'Mandsaur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '311', 'name' => 'Morena', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '312', 'name' => 'Narsinghpur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '313', 'name' => 'Neemuch', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '314', 'name' => 'Panna', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '315', 'name' => 'Rewa', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '316', 'name' => 'Rajgarh', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '317', 'name' => 'Ratlam', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '318', 'name' => 'Raisen', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '319', 'name' => 'Sagar', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '320', 'name' => 'Satna', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '321', 'name' => 'Sehore', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '322', 'name' => 'Seoni', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '323', 'name' => 'Shahdol', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '324', 'name' => 'Shajapur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '325', 'name' => 'Sheopur', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '326', 'name' => 'Shivpuri', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '327', 'name' => 'Sidhi', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '328', 'name' => 'Singrauli', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '329', 'name' => 'Tikamgarh', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '330', 'name' => 'Ujjain', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '331', 'name' => 'Umaria', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '332', 'name' => 'Vidisha', 'state_id' => '20', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '333', 'name' => 'Ahmednagar', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '334', 'name' => 'Akola', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '335', 'name' => 'Amravati', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '336', 'name' => 'Aurangabad', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '337', 'name' => 'Bhandara', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '338', 'name' => 'Beed', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '339', 'name' => 'Buldhana', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '340', 'name' => 'Chandrapur', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '341', 'name' => 'Dhule', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '342', 'name' => 'Gadchiroli', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '343', 'name' => 'Gondia', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '344', 'name' => 'Hingoli', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '345', 'name' => 'Jalgaon', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '346', 'name' => 'Jalna', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '347', 'name' => 'Kolhapur', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '348', 'name' => 'Latur', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '349', 'name' => 'Mumbai City', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '350', 'name' => 'Mumbai suburban', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '351', 'name' => 'Nandurbar', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '352', 'name' => 'Nanded', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '353', 'name' => 'Nagpur', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '354', 'name' => 'Nashik', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '355', 'name' => 'Osmanabad', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '356', 'name' => 'Parbhani', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '357', 'name' => 'Pune', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '358', 'name' => 'Raigad', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '359', 'name' => 'Ratnagiri', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '360', 'name' => 'Sindhudurg', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '361', 'name' => 'Sangli', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '362', 'name' => 'Solapur', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '363', 'name' => 'Satara', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '364', 'name' => 'Thane', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '365', 'name' => 'Wardha', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '366', 'name' => 'Washim', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '367', 'name' => 'Yavatmal', 'state_id' => '21', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '368', 'name' => 'Amritsar', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '369', 'name' => 'Barnala', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '370', 'name' => 'Bathinda', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '371', 'name' => 'Firozpur', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '372', 'name' => 'Faridkot', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '373', 'name' => 'Fatehgarh Sahib', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '374', 'name' => 'Fazilka', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '375', 'name' => 'Gurdaspur', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '376', 'name' => 'Hoshiarpur', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '377', 'name' => 'Jalandhar', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '378', 'name' => 'Kapurthala', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '379', 'name' => 'Ludhiana', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '380', 'name' => 'Mansa', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '381', 'name' => 'Moga', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '382', 'name' => 'Sri Muktsar Sahib', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '383', 'name' => 'Pathankot', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '384', 'name' => 'Patiala', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '385', 'name' => 'Rupnagar', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '386', 'name' => 'Ajitgarh (Mohali)', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '387', 'name' => 'Sangrur', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '388', 'name' => 'Nawanshahr', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '389', 'name' => 'Tarn Taran', 'state_id' => '28', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '390', 'name' => 'Ajmer', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '391', 'name' => 'Alwar', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '392', 'name' => 'Bikaner', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '393', 'name' => 'Barmer', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '394', 'name' => 'Banswara', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '395', 'name' => 'Bharatpur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '396', 'name' => 'Baran', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '397', 'name' => 'Bundi', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '398', 'name' => 'Bhilwara', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '399', 'name' => 'Churu', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '400', 'name' => 'Chittorgarh', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '401', 'name' => 'Dausa', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '402', 'name' => 'Dholpur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '403', 'name' => 'Dungapur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '404', 'name' => 'Ganganagar', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '405', 'name' => 'Hanumangarh', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '406', 'name' => 'Jhunjhunu', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '407', 'name' => 'Jalore', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '408', 'name' => 'Jodhpur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '409', 'name' => 'Jaipur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '410', 'name' => 'Jaisalmer', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '411', 'name' => 'Jhalawar', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '412', 'name' => 'Karauli', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '413', 'name' => 'Kota', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '414', 'name' => 'Nagaur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '415', 'name' => 'Pali', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '416', 'name' => 'Pratapgarh', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '417', 'name' => 'Rajsamand', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '418', 'name' => 'Sikar', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '419', 'name' => 'Sawai Madhopur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '420', 'name' => 'Sirohi', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '421', 'name' => 'Tonk', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '422', 'name' => 'Udaipur', 'state_id' => '29', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '423', 'name' => 'East Sikkim', 'state_id' => '30', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '424', 'name' => 'North Sikkim', 'state_id' => '30', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '425', 'name' => 'South Sikkim', 'state_id' => '30', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '426', 'name' => 'West Sikkim', 'state_id' => '30', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '427', 'name' => 'Ariyalur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '428', 'name' => 'Chennai', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '429', 'name' => 'Coimbatore', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '430', 'name' => 'Cuddalore', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '431', 'name' => 'Dharmapuri', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '432', 'name' => 'Dindigul', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '433', 'name' => 'Erode', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '434', 'name' => 'Kanchipuram', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '435', 'name' => 'Kanyakumari', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '436', 'name' => 'Karur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '437', 'name' => 'Madurai', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '438', 'name' => 'Nagapattinam', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '439', 'name' => 'Nilgiris', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '440', 'name' => 'Namakkal', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '441', 'name' => 'Perambalur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '442', 'name' => 'Pudukkottai', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '443', 'name' => 'Ramanathapuram', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '444', 'name' => 'Salem', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '445', 'name' => 'Sivaganga', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '446', 'name' => 'Tirupur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '447', 'name' => 'Tiruchirappalli', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '448', 'name' => 'Theni', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '449', 'name' => 'Tirunelveli', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '450', 'name' => 'Thanjavur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '451', 'name' => 'Thoothukudi', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '452', 'name' => 'Tiruvallur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '453', 'name' => 'Tiruvarur', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '454', 'name' => 'Tiruvannamalai', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '455', 'name' => 'Vellore', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '456', 'name' => 'Viluppuram', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '457', 'name' => 'Virudhunagar', 'state_id' => '31', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '458', 'name' => 'Agra', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '459', 'name' => 'Allahabad', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '460', 'name' => 'Aligarh', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '461', 'name' => 'Ambedkar Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '462', 'name' => 'Auraiya', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '463', 'name' => 'Azamgarh', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '464', 'name' => 'Barabanki', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '465', 'name' => 'Budaun', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '466', 'name' => 'Bagpat', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '467', 'name' => 'Bahraich', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '468', 'name' => 'Bijnor', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '469', 'name' => 'Ballia', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '470', 'name' => 'Banda', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '471', 'name' => 'Balrampur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '472', 'name' => 'Bareilly', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '473', 'name' => 'Basti', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '474', 'name' => 'Bulandshahr', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '475', 'name' => 'Chandauli', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '476', 'name' => 'Chhatrapati Shahuji Maharaj Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '477', 'name' => 'Chitrakoot', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '478', 'name' => 'Deoria', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '479', 'name' => 'Etah', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '480', 'name' => 'Kanshi Ram Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '481', 'name' => 'Etawah', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '482', 'name' => 'Firozabad', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '483', 'name' => 'Farrukhabad', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '484', 'name' => 'Fatehpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '485', 'name' => 'Faizabad', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '486', 'name' => 'Gautam Buddh Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '487', 'name' => 'Gonda', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '488', 'name' => 'Ghazipur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '489', 'name' => 'Gorakhpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '490', 'name' => 'Ghaziabad', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '491', 'name' => 'Hamirpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '492', 'name' => 'Hardoi', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '493', 'name' => 'Mahamaya Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '494', 'name' => 'Jhansi', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '495', 'name' => 'Jalaun', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '496', 'name' => 'Jyotiba Phule Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '497', 'name' => 'Jaunpur district', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '498', 'name' => 'Ramabai Nagar (Kanpur Dehat)', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '499', 'name' => 'Kannauj', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '500', 'name' => 'Kanpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '501', 'name' => 'Kaushambi', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '502', 'name' => 'Kushinagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '503', 'name' => 'Lalitpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '504', 'name' => 'Lakhimpur Kheri', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '505', 'name' => 'Lucknow', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '506', 'name' => 'Mau', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '507', 'name' => 'Meerut', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '508', 'name' => 'Maharajganj', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '509', 'name' => 'Mahoba', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '510', 'name' => 'Mirzapur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '511', 'name' => 'Moradabad', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '512', 'name' => 'Mainpuri', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '513', 'name' => 'Mathura', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '514', 'name' => 'Muzaffarnagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '515', 'name' => 'Panchsheel Nagar district (Hapur)', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '516', 'name' => 'Pilibhit', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '517', 'name' => 'Shamli', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '518', 'name' => 'Pratapgarh', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '519', 'name' => 'Rampur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '520', 'name' => 'Raebareli', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '521', 'name' => 'Saharanpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '522', 'name' => 'Sitapur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '523', 'name' => 'Shahjahanpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '524', 'name' => 'Sant Kabir Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '525', 'name' => 'Siddharthnagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '526', 'name' => 'Sonbhadra', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '527', 'name' => 'Sant Ravidas Nagar', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '528', 'name' => 'Sultanpur', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '529', 'name' => 'Shravasti', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '530', 'name' => 'Unnao', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '531', 'name' => 'Varanasi', 'state_id' => '34', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '532', 'name' => 'Almora', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '533', 'name' => 'Bageshwar', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '534', 'name' => 'Chamoli', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '535', 'name' => 'Champawat', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '536', 'name' => 'Dehradun', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '537', 'name' => 'Haridwar', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '538', 'name' => 'Nainital', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '539', 'name' => 'Pauri Garhwal', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '540', 'name' => 'Pithoragarh', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '541', 'name' => 'Rudraprayag', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '542', 'name' => 'Tehri Garhwal', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '543', 'name' => 'Udham Singh Nagar', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '544', 'name' => 'Uttarkashi', 'state_id' => '35', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '545', 'name' => 'Birbhum', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '546', 'name' => 'Bankura', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '547', 'name' => 'Bardhaman', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '548', 'name' => 'Darjeeling', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '549', 'name' => 'Dakshin Dinajpur', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '550', 'name' => 'Hooghly', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '551', 'name' => 'Howrah', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '552', 'name' => 'Jalpaiguri', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '553', 'name' => 'Cooch Behar', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '554', 'name' => 'Kolkata', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '555', 'name' => 'Maldah', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '556', 'name' => 'Paschim Medinipur', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '557', 'name' => 'Purba Medinipur', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '558', 'name' => 'Murshidabad', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '559', 'name' => 'Nadia', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '560', 'name' => 'North 24 Parganas', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '561', 'name' => 'South 24 Parganas', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '562', 'name' => 'Purulia', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '563', 'name' => 'Uttar Dinajpur', 'state_id' => '36', 'created_at' => NULL, 'updated_at' => NULL),
            ]);
    }
}
