<?php

namespace App\Uploads;

use Illuminate\Database\Eloquent\Model;

class Setlement extends Model
{
    //
    protected $fillable=['Month','REQUEST_NO','LOAN_NO','CUSTOMERNAME','BRANCH','STATE','PRODUCT_1','SCHEMEDESC','PENALTY','LOANAMT','EMI','SETTLEMENTAMT',
        'REQUEST_DATE','REQUESTED_BY',
        'SETTLEMENTSTART_DATE',
        'SETTLEMENTEND_DATE','SETTLEMENT_STROKES','MAKER_REMARKS','VERIFIER_REMARKS',
        'VERIFIED_DATE','VERIFIER','APPROVER_REAMRKS',
        'APPROVED_DATE','APPROVER','STATUS1','APPROVED_BY',
        'STATUS_DATE','APPROVER_EMAIL','TOTAL_POS','CURRENT_MONTH_INTEREST','INSTALLMENT_OVERDUE','TOTAL_OVERDUE_PRINCIPAL','TOTAL_OVERDUE_INTEREST','PENALTYCHARGES','ST_ON_PENALTY','BOUNCE_CHARGES','PENAL_CHARGES','OTHER_CHARGES','TOTAL_DUES','TOTAL_POSCOLL','CURRENT_MONTH_INTERESTCOLL','INSTALLMENT_OVERDUECOLL','TOTAL_OVERDUE_PRINCIPALCOLL','TOTAL_OVERDUE_INTERESTCOLL','PENALTYCOLLECTED','ST_ON_FC_CHARGESCOLL','BOUNCE_CHARGESCOLL','PENAL_CHARGESCOLL','OTHER_CHARGESCOLL','TOTAL_AMOUNT_COLLECTED','TOTAL_POSWAIVER','CURRENT_MONTH_INTERESTWAIVER','INSTALLMENT_OVERDUEWAIVER','TOTAL_OVERDUE_PRINCIPALWAIVER','TOTAL_OVERDUE_INTERESTWAIVER','PENALTYWIAVER','ST_ON_FC_CHARGESWAIVER','BOUNCE_CHARGESWAIVER','PENAL_CHARGESWAIVER','OTHER_CHARGESWAIVER','TOTAL_WAIVER','TOTAL_CHARGES_WAIVER','per_of_POS_Waiver','per_of_Charges_Waiver','BUCKET','DPD','DPDSTRING','STAGE','LOAN_STATUS','PAYMENT_RECEIVED',
        'LAST_PAYMENT_DATE','SYSTEM','Product1','Status2','Hold_Category','Remark',
        'Received_Date',
        '1st_action_date',
        'Hold_Date',
        'Resolution_Date',
        'Action_Date','Status3','Request_received_month','TOTAL_SETTLEMENT_AMT','Agency_Name','SETTLEMENT_Close_day','SETTLEMENT_Status','DAC_Amount','Online_Amount','Total_Payment_Reacive','SETTLEMENTAMT_Amount_Status','Amount_Deffrance','PRODUCT','BUCKET_Q','DAC_Received',
        'Online_pay_date',
        'Actual_Date',
        'Date_GAP',
        'Date_GAP_BKT',
        'Scheme',
        'lob'
];
    protected $table="settlement";
}
